language: python
python:
  - "3.6-dev"  # 3.6 development branch

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coverage
# command to run tests
script:
  - py.test --cov=tests/

after_success:
  -coveralls